import { useEffect, useState } from 'react';
import HomePage from '../components/HomePage';
import Head from 'next/head';
import dummyImage1 from '../public/240_F_309869755_IquCHHxF7YABo2odctUGEjMrgVDSM8qV.jpg';
import dummyImage2 from '../public/aykut-aktas-Dy4-Fer7zwc-unsplash.jpg';
import dummyImage3 from '../public/ayo-ogunseinde-6W4F62sN_yI-unsplash.jpg';
import dummyImage4 from '../public/corey-saldana-pIKQbdSzF_k-unsplash.jpg';
import dummyImage5 from '../public/mahdi-chaghari-BGMuQUY91w4-unsplash.jpg';
import dummyImage6 from '../public/pexels-andrea-piacquadio-974911.jpg';
import dummyImage7 from '../public/radu-florin-OP8655xgBjo-unsplash.jpg';
import dummyImage8 from '../public/tamanna-rumee-eD1RNYzzUxc-unsplash.jpg';

const DUMMY_DATA = [
  {
    title: 'smartphones',
    url: [
      dummyImage1,
      dummyImage3,
      dummyImage4,
      dummyImage5,
      dummyImage6,
      dummyImage7,
      dummyImage8,
    ],
  },
  {
    title: 'clothes',
    url: [
      dummyImage1,
      dummyImage3,
      dummyImage4,
      dummyImage5,
      dummyImage6,
      dummyImage7,
      dummyImage8,
    ],
  },
  {
    title: 'footwear',
    url: [
      dummyImage1,
      dummyImage3,
      dummyImage4,
      dummyImage5,
      dummyImage6,
      dummyImage7,
      dummyImage8,
    ],
  },
];

interface homeProps {
  products: [{ title: string; url: string[] }];
}

export default function Home(props: homeProps) {
  const { products } = props;
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage products={props.products} />
    </div>
  );
}

export async function getStaticProps() {
  // const categories: string[] = [];
  // const data = await fetch('https://dummyjson.com/products/categories');
  // const res = await data.json();
  // res.forEach((cat: string) => categories.push(cat));
  // const mainPageData: [{ title: string; url: string[] }] = [
  //   { title: '', url: [] },
  // ]; // data for the main page will be fetch by unplash and then shown to the main page when the user will click on it it will show on the screen

  return {
    props: {
      products: DUMMY_DATA,
    },
  };
}
