import HomePage from '../components/HomePage';
import Head from 'next/head';

interface homeProps {
  products: [{ title: string; url: string[] }];
}

export default function Home(props: homeProps) {
  return (
    <div className="w-full">
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage products={props.products} />
    </div>
  );
}

export async function getServerSideProps() {
  const { products } = await import('../public/data.json');
  return {
    props: {
      products: products,
    },
  };
}
